name: Docker (build & test)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        # Tag the image with the commit SHA so builds are unique
        docker build -t nearn_ft:${{ github.sha }} .

    - name: Run cargo build inside container
      run: docker run --rm nearn_ft:${{ github.sha }} cargo build --verbose

    - name: Run cargo tests inside container
      run: docker run --rm nearn_ft:${{ github.sha }} cargo test --verbose
